INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (1, null, 'Banking', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (2, null, 'Bank fee', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (3, null, 'Currency fee', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (4, null, 'Transfer OUT', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (5, null, 'Cash withdrawal', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (6, null, 'ATM', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (7, null, 'Home Payment', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (8, null, 'Rent', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (9, null, 'Mortgage', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (10, null, 'Utility Bills', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (11, null, 'Electricity', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (12, null, 'Internet', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (13, null, 'Gas', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (14, null, 'Management fee', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (15, null, 'Waste mgmt', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (16, null, 'Groceries', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (17, null, 'Pharmacy', 'OUT', 35);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (18, null, 'Shopping', 'OUT', 18);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (19, null, 'Electronics', 'OUT', 18);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (20, null, 'Clothes', 'OUT', 18);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (21, null, 'Home equipment', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (22, null, 'Furniture', 'OUT', 21);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (23, null, 'Appliances', 'OUT', 21);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (24, null, 'Cleaning services', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (26, null, 'Restaurants', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (27, null, 'Pubs & Bars', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (28, null, 'Take away', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (29, null, 'Transport', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (30, null, 'Taxi', 'OUT', 29);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (31, null, 'Bus', 'OUT', 29);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (32, null, 'Train', 'OUT', 29);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (33, null, 'Flights', 'OUT', 29);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (34, null, 'Leap card', 'OUT', 29);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (35, null, 'Beauty', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (36, null, 'Health', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (37, null, 'GP', 'OUT', 36);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUES (38, null, 'Veterinary', 'OUT', 36);
