INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (1, null, 'Banking', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (2, null, 'Bank fee', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (3, null, 'Currency fee', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (4, null, 'Transfer OUT', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (5, null, 'Cash withdrawal', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (6, null, 'ATM', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (7, null, 'Home Payment', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (8, null, 'Rent', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (9, null, 'Mortgage', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (10, null, 'Utility Bills', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (11, null, 'Electricity', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (12, null, 'Internet', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (13, null, 'Gas', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (14, null, 'Management fee', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (15, null, 'Waste mgmt', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (16, null, 'Groceries', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (17, null, 'Pharmacy', 'OUT', 35);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (18, null, 'Shopping', 'OUT', 18);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (19, null, 'Electronics', 'OUT', 18);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (20, null, 'Clothes', 'OUT', 18);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (21, null, 'Home equipment', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (22, null, 'Furniture', 'OUT', 21);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (23, null, 'Appliances', 'OUT', 21);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (24, null, 'Cleaning services', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (26, null, 'Restaurants', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (27, null, 'Pubs & Bars', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (28, null, 'Take away', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (29, null, 'Transport', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (30, null, 'Taxi', 'OUT', 29);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (31, null, 'Bus', 'OUT', 29);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (32, null, 'Train', 'OUT', 29);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (33, null, 'Flights', 'OUT', 29);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (34, null, 'Leap card', 'OUT', 29);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (35, null, 'Beauty', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (36, null, 'Health', 'OUT', NULL);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (37, null, 'GP', 'OUT', 36);
INSERT INTO category (id, user_id, name, flow, parent_id) VALUE (38, null, 'Veterinary', 'OUT', 36);
